#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Feb 01 19:38:38 CET 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim switch_tb_behav -key {Behavioral:sim_1:Functional:switch_tb} -tclbatch switch_tb.tcl -log simulate.log"
xsim switch_tb_behav -key {Behavioral:sim_1:Functional:switch_tb} -tclbatch switch_tb.tcl -log simulate.log

